### ISSUE TITLE
CDN doesn't allow to be grabbed from another site

### ISSUE THREAD

**Issue by blained3** [signalfx/splunk-otel-js-web#115]
I get the following error:
`Access to script at 'https://cdn.signalfx.com/o11y-gdi-rum/latest/splunk-otel-web.js' from origin 'https://www.whiscuit.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I believe the solution is here: https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/

**Comment by jtmalinowski** [comment]
hey @blained3, thanks for letting us know! We've misconfigured a caching policy, and as luck would have it, the first request to reach Cloud Front was non-CORS. I'll let you close the issue if it looks good for you now.

**Comment by jtmalinowski** [comment]
Feel free to reopen if you can still find any issues related to this.
