### ISSUE TITLE
Support for 64bit traceId in Server-Timing response header

### ISSUE THREAD

**Issue by tomasporemba** [signalfx/splunk-otel-js-web#297]
Hello, I have a question about tracing and `Server-Timing` response header format expected by the instrumentation script.

Is there any reason, why the instrumentation does not support 64bit traceIds?
If I understood correctly, the `traceId` should be valid for b3-propagation (both 64bit and 128bit identifiers are valid as per https://github.com/openzipkin/b3-propagation#traceid).
Current [servertiming.ts](https://github.com/signalfx/splunk-otel-js-web/blob/main/src/servertiming.ts) implementation asks for 32hex `traceId` identifiers (specifically [here](https://github.com/signalfx/splunk-otel-js-web/blob/main/src/servertiming.ts#L29) and [here](https://github.com/signalfx/splunk-otel-js-web/blob/main/src/servertiming.ts#L42)).

We are not using Splunk agent on the server side for automatic instrumentation of the code and our `traceId`s are 64bit long. This prevents us effectively from linking traces from server and client as the Splunk RUM does not pick up the `Server-Timing` header.

Am I missing something? Would it be possible to support shorter `traceId`s as well?

**Comment by johnbley** [comment]
Hi Tomas - 
We're using the nascent standard documented here: https://www.w3.org/TR/trace-context/#traceparent-header, which is explicit in its format - 32 hex chars for the traceId.  Smaller traceIds are fine but need to be left-padded with 0s to fit: https://www.w3.org/TR/trace-context/#interoperating-with-existing-systems-which-use-shorter-identifiers.  Assuming you're trying to do this by rolling your own server-side generator for this feature, you can read all about it at https://github.com/signalfx/splunk-otel-js-web/blob/main/docs/ServerTraceContext.md.  Hope that helps!

**Comment by tomasporemba** [comment]
Hi @johnbley ,
thanks for the quick reply.
I am a bit confused. [This link](https://github.com/signalfx/splunk-otel-js-web/blob/main/docs/ServerTraceContext.md) talks only about sending a `Server-Timing` header (as it says it is supposed to be enough to link Splunk RUM traces with BE traces). Are we supposed to consume (on the server) the `traceparent` header that is generated by instrumented client code as well?

**Comment by johnbley** [comment]
No, the `Server-Timing` response header is all that is needed.
